'use client';
import { useEffect, useRef, useState } from 'react';
import { Button, Field } from '@/components/workbench/ui';
import type { Project, VideoDraft, VideoShot, MediaFile, SiteSpec } from '@/features/projects/model';
import { api, outputUrl, uploadOutput } from '@/features/projects/server-store';
import { audioSource, composeSource, shotSource, validateSite } from '@/lib/workbench/output-contract.mjs';
import type { EditProject, Notice } from './stages';
import type { GenerationControls } from './generation-api';
import type { GenerationTask } from './task-results';

type Props={project:Project;edit:EditProject;generation?:GenerationControls;notice:Notice};
const emptyVideo=():VideoDraft=>({ratio:'16:9',shots:[],keepAudio:false,burnSubtitles:true});
function DownloadFile({fileId,name,children}:{fileId:string;name:string;children:React.ReactNode}) {
  const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  return <><a href={outputUrl(fileId)} download={name} aria-disabled={busy} onClick={async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch(outputUrl(fileId),{signal:AbortSignal.timeout(240000)});if(!response.ok)throw new Error('文件下载失败，请稍后重试。');const url=URL.createObjectURL(await response.blob());const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){setError(e instanceof Error?e.message:'下载未完成。');}finally{setBusy(false);}}}>{busy?'正在读取文件…':children}</a>{error&&<p role="alert">{error}</p>}</>;
}
function MediaUpload({label,kind,onUpload,notice}:{label:string;kind:'mp4'|'wav';onUpload:(file:MediaFile)=>void;notice:Notice}) {
  const input=useRef<HTMLInputElement>(null);const[busy,setBusy]=useState(false);
  return <><Button variant="secondary" disabled={busy} onClick={()=>input.current?.click()}>{busy?'正在处理文件…':label}</Button><input hidden ref={input} type="file" accept={kind==='mp4'?'.mp4,video/mp4':'.wav,.mp3,.m4a,audio/*'} aria-label={label} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{onUpload(await uploadOutput(file,kind));notice('文件已解码并保存。');}catch(error){notice(error instanceof Error?error.message:'文件未能保存。');}finally{setBusy(false);}}}/></>;
}
export function WebsitePreview({fileId}:{fileId:string}) {
  const[mobile,setMobile]=useState(false);
  return <div className="site-output"><div className="inline-actions"><Button variant={!mobile?'secondary':'ghost'} onClick={()=>setMobile(false)}>桌面预览</Button><Button variant={mobile?'secondary':'ghost'} onClick={()=>setMobile(true)}>手机预览</Button><span className="muted">可点击导航、搜索和展开内容</span></div><div className={'site-frame '+(mobile?'is-mobile':'')}><iframe title="生成网站交互预览" src={outputUrl(fileId)} sandbox="allow-scripts" referrerPolicy="no-referrer" /></div></div>;
}
export function OutputTaskPreview({task}:{task:GenerationTask}) {
  const r=task.result;if(!r)return null;
  const file=r.videoClip||r.videoFinal;
  return <>
    {r.videoPlan&&<Field label="分镜结果预览"><textarea readOnly rows={8} value={r.videoPlan.shots.map((s,i)=>`${i+1}. ${s.title} · ${s.duration} 秒\n画面：${s.visual}\n运镜：${s.camera}\n旁白：${s.narration||'无'}\n字幕：${s.subtitle||'无'}`).join('\n\n')}/></Field>}
    {file&&<div className="media-result"><video controls preload="metadata" src={outputUrl(file.fileId)} aria-label="生成视频预览"/><DownloadFile fileId={file.fileId} name="创意视频.mp4">下载 MP4</DownloadFile>{r.videoFinal&&<DownloadFile fileId={r.videoFinal.subtitleFileId} name="字幕.srt">下载字幕 SRT</DownloadFile>}</div>}
    {r.videoAudio&&<div className="media-result"><audio controls src={outputUrl(r.videoAudio.fileId)}/><DownloadFile fileId={r.videoAudio.fileId} name="旁白.wav">下载旁白</DownloadFile></div>}
    {r.website&&<><p>网站包含 {r.website.spec.pages.map(p=>p.title).join('、')}。</p>{r.website.spec.limitations.length>0&&<p role="status">尚未实现的要求：{r.website.spec.limitations.join('；')}</p>}<details><summary>预览新网站</summary>{r.website.previewFileId&&<WebsitePreview fileId={r.website.previewFileId}/>}</details>{r.website.zipFileId&&<DownloadFile fileId={r.website.zipFileId} name="网站源码.zip">下载网站源码与素材 ZIP</DownloadFile>}</>}
  </>;
}
export function VideoOutput({project,edit,generation,notice}:Props) {
  const video=project.video||emptyVideo();const[provider,setProvider]=useState('workbuddy');
  useEffect(()=>{api<{video:{provider:string}}>('status').then(s=>setProvider(s.video.provider)).catch(()=>{});},[]);
  const update=(fn:(v:VideoDraft)=>VideoDraft)=>edit(p=>p.id===project.id?{...p,video:fn(p.video||emptyVideo())}:p);
  const shotEdit=(id:string,fn:(s:VideoShot)=>VideoShot)=>update(v=>({...v,shots:v.shots.map(s=>s.id===id?fn(s):s)}));
  const total=video.shots.reduce((n,s)=>n+s.duration,0);
  const finalCurrent=video.final?.source===composeSource(video);
  return <div className="stage-stack">
    <section className="surface"><div className="section-heading"><div><h3>把脚本变成一段完整视频</h3><p>先采用分镜，再为每个镜头生成或导入视频，最后自动合成。修改某个镜头可单独重做。</p></div><span className="tag tag-soft">视频</span></div>
      <div className="delivery-fields"><Field label="视频生成服务"><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="workbuddy">WorkBuddy</option><option value="external">外部 API · Runway Gen-4.5 协议</option></select></Field><Field label="目标时长"><input value={project.delivery.duration} placeholder="例如 30 秒，最多 120 秒" onChange={e=>edit(p=>({...p,delivery:{...p.delivery,duration:e.target.value}}))}/></Field><Field label="画幅"><select value={video.ratio} onChange={e=>{const ratio=e.target.value as VideoDraft['ratio'];edit(p=>({...p,delivery:{...p.delivery,ratio},video:{...(p.video||emptyVideo()),ratio}}));}}><option>16:9</option><option>9:16</option></select></Field></div>
      <Field label="视频补充要求"><textarea rows={2} value={project.delivery.notes} onChange={e=>edit(p=>({...p,delivery:{...p.delivery,notes:e.target.value}}))}/></Field>
      <div className="generation-row"><span className="muted">每镜头 2–10 秒，最多 12 镜头。首帧参考有助于保持视觉方向，角色一致性需预览检查。</span><Button disabled={generation?.busy} onClick={()=>generation?.run('video-plan',{action:'generate'})}>{video.shots.length?'重新规划分镜':'生成分镜方案'}</Button></div>
    </section>
    {video.shots.length>0&&<section className="surface"><div className="section-heading"><h3>镜头与声音 · {total} 秒</h3><span className="muted">旧文件会保留，采用新结果后才替换</span></div><div className="shot-list">{video.shots.map((s,i)=><article className="shot-editor" key={s.id}>
      <div className="section-heading"><h4>镜头 {i+1} · {s.title}</h4><div className="inline-actions"><Button variant="ghost" disabled={i===0} onClick={()=>update(v=>{const shots=[...v.shots];[shots[i-1],shots[i]]=[shots[i],shots[i-1]];return {...v,shots};})}>上移</Button><Button variant="ghost" onClick={()=>{const old=video;update(v=>({...v,shots:v.shots.filter(x=>x.id!==s.id)}));notice('已移除镜头',()=>update(()=>old));}}>移除</Button></div></div>
      <div className="delivery-fields"><Field label={`镜头 ${i+1} 名称`}><input value={s.title} onChange={e=>shotEdit(s.id,s=>({...s,title:e.target.value}))}/></Field><Field label={`镜头 ${i+1} 秒数`}><input type="number" min={2} max={10} value={s.duration} onChange={e=>shotEdit(s.id,s=>({...s,duration:Math.min(10,Math.max(2,Math.round(Number(e.target.value)||2)))}))}/></Field><Field label={`镜头 ${i+1} 首帧参考`}><select value={s.referenceAssetId||''} onChange={e=>shotEdit(s.id,s=>({...s,referenceAssetId:e.target.value||undefined}))}><option value="">仅文字生成</option>{project.assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field></div>
      <Field label={`镜头 ${i+1} 画面`}><textarea rows={3} value={s.visual} onChange={e=>shotEdit(s.id,s=>({...s,visual:e.target.value}))}/></Field><Field label={`镜头 ${i+1} 运镜与保持项`}><textarea rows={2} value={s.camera} onChange={e=>shotEdit(s.id,s=>({...s,camera:e.target.value}))}/></Field><Field label={`镜头 ${i+1} 重生成修改要求`}><input value={s.revision} placeholder="重生成会带入这些修改；满意后采用新视频" onChange={e=>shotEdit(s.id,s=>({...s,revision:e.target.value}))}/></Field>
      <div className="inline-actions"><Button disabled={generation?.busy} onClick={()=>generation?.run('video-shot',{objectId:s.id,provider})}>{s.clip?'重新生成此镜头':'生成此镜头'}</Button><MediaUpload label={`导入镜头 ${i+1} MP4`} kind="mp4" notice={notice} onUpload={file=>shotEdit(s.id,current=>({...current,clip:{...file,source:shotSource(s,video.ratio)}}))}/></div>
      {s.clip&&<><video className="shot-player" controls preload="metadata" src={outputUrl(s.clip.fileId)} aria-label={`镜头 ${i+1} 预览`}/><p className="muted">实际 {s.clip.duration.toFixed(1)} 秒{ s.clip.source!==shotSource(s,video.ratio)?' · 分镜已修改，合成前请重生成或重新导入。':''}</p></>}
      <div className="audio-fields"><Field label={`镜头 ${i+1} 旁白`}><textarea rows={2} value={s.narration} placeholder="无需配音时留空；填写后须提供对应音频" onChange={e=>shotEdit(s.id,s=>({...s,narration:e.target.value}))}/></Field><Field label={`镜头 ${i+1} 字幕`}><textarea rows={2} value={s.subtitle} placeholder="准确字幕；无需字幕时留空" onChange={e=>shotEdit(s.id,s=>({...s,subtitle:e.target.value}))}/></Field></div>
      {s.narration.trim()&&<><div className="inline-actions"><Button variant="secondary" disabled={generation?.busy} onClick={()=>generation?.run('video-audio',{objectId:s.id})}>通过 WorkBuddy 生成旁白</Button><MediaUpload label={`导入镜头 ${i+1} 配音`} kind="wav" notice={notice} onUpload={file=>shotEdit(s.id,current=>({...current,audio:{...file,source:audioSource(s)}}))}/></div>{s.audio&&<><audio controls src={outputUrl(s.audio.fileId)} aria-label={`镜头 ${i+1} 配音`}/>{s.audio.source!==audioSource(s)&&<p role="status">旁白已修改，请重新提供配音。</p>}</>}</>}
    </article>)}</div><Button variant="secondary" disabled={video.shots.length>=12} onClick={()=>update(v=>({...v,shots:[...v.shots,{id:crypto.randomUUID(),title:'新镜头',visual:'',camera:'',duration:5,narration:'',subtitle:'',revision:''}]}))}>添加镜头</Button></section>}
    {video.shots.length>0&&<section className="surface"><h3>合成与交付</h3><div className="inline-actions"><label><input type="checkbox" checked={video.burnSubtitles} onChange={e=>update(v=>({...v,burnSubtitles:e.target.checked}))}/> 将字幕烧录到画面</label><label><input type="checkbox" checked={video.keepAudio} onChange={e=>update(v=>({...v,keepAudio:e.target.checked}))}/> 无单独配音时保留镜头原声</label></div><div className="inline-actions"><MediaUpload label="添加背景音乐" kind="wav" notice={notice} onUpload={file=>update(v=>({...v,music:file}))}/>{video.music&&<><audio controls src={outputUrl(video.music.fileId)} aria-label="背景音乐"/><Button variant="ghost" onClick={()=>update(v=>({...v,music:undefined}))}>移除配乐</Button></>}</div><p className="muted">单独配音替换该镜头原声；配乐以低音量循环至结尾。过短视频或过长配音会提示调整，不静默省略旁白。</p><Button disabled={generation?.busy} onClick={()=>generation?.run('video-compose')}>合成完整视频</Button></section>}
    {video.final&&<section className="surface"><h3>{finalCurrent?'已采用的视频成品':'已采用的旧版视频'}</h3>{!finalCurrent&&<p role="status">镜头或声音设置已修改；下方保留上一版成品，重新合成后可采用新版。</p>}<OutputTaskPreview task={{result:{videoFinal:video.final}} as GenerationTask}/></section>}
  </div>;
}
export function WebsiteOutput({project,edit,generation,notice}:Props) {
  const site=project.website;const[pageIndex,setPageIndex]=useState(0);const[raw,setRaw]=useState('');
  useEffect(()=>{setRaw(site?JSON.stringify(site.spec,null,2):'');},[site?.spec]);
  const index=Math.min(pageIndex,(site?.spec.pages.length||1)-1);const page=site?.spec.pages[index];
  const change=(fn:(spec:SiteSpec)=>SiteSpec)=>edit(p=>p.website?{...p,website:{...p.website,spec:fn(p.website.spec)}}:p);
  const dirty=site&&JSON.stringify(site.spec)!==JSON.stringify(site.builtSpec);
  return <div className="stage-stack"><section className="surface"><div className="section-heading"><div><h3>让文化内容成为可浏览的网站</h3><p>根据内容方案、视觉方向和选定素材生成静态专题网站，支持导航、搜索筛选和折叠问答。</p></div><span className="tag tag-soft">网站</span></div><Field label="网站交付要求"><textarea rows={3} value={project.delivery.notes} placeholder="例如：两个页面，作品图库可以按分类筛选，手机也能浏览" onChange={e=>edit(p=>({...p,delivery:{...p.delivery,notes:e.target.value}}))}/></Field><div className="generation-row"><span className="muted">沿用文字模型。源码包含页面、素材与离线运行说明；登录、支付和数据库需后续开发。</span><Button disabled={generation?.busy} onClick={()=>generation?.run('website',{action:'generate'})}>{site?'重新生成网站':'生成网站'}</Button></div></section>
    {site&&<><section className="surface"><h3>编辑网站内容</h3><div className="delivery-fields"><Field label="网站名称"><input value={site.spec.title} onChange={e=>change(s=>({...s,title:e.target.value}))}/></Field><Field label="网站主题"><select value={site.spec.theme} onChange={e=>change(s=>({...s,theme:e.target.value as SiteSpec['theme']}))}><option value="paper">浅色纸感</option><option value="night">深色展厅</option></select></Field><Field label="网站主题色"><input type="color" value={site.spec.accent} onChange={e=>change(s=>({...s,accent:e.target.value}))}/></Field></div><Field label="网站介绍"><textarea rows={2} value={site.spec.description} onChange={e=>change(s=>({...s,description:e.target.value}))}/></Field><Field label="编辑页面"><select value={index} onChange={e=>setPageIndex(Number(e.target.value))}>{site.spec.pages.map((p,i)=><option key={p.id} value={i}>{p.title}</option>)}</select></Field>
      {page&&<><Field label="页面标题"><input value={page.title} onChange={e=>change(s=>({...s,pages:s.pages.map((p,i)=>i===index?{...p,title:e.target.value}:p)}))}/></Field><Field label="页面引言"><textarea rows={3} value={page.intro} onChange={e=>change(s=>({...s,pages:s.pages.map((p,i)=>i===index?{...p,intro:e.target.value}:p)}))}/></Field>{page.sections.map((section,si)=><details key={si}><summary>{section.title}</summary><Field label={`内容区 ${si+1} 正文`}><textarea rows={4} value={section.body} onChange={e=>change(s=>({...s,pages:s.pages.map((p,i)=>i===index?{...p,sections:p.sections.map((v,n)=>n===si?{...v,body:e.target.value}:v)}:p)}))}/></Field>{section.items.map((item,ii)=><Field key={ii} label={item.title}><textarea rows={3} value={item.text} onChange={e=>change(s=>({...s,pages:s.pages.map((p,i)=>i===index?{...p,sections:p.sections.map((v,n)=>n===si?{...v,items:v.items.map((x,j)=>j===ii?{...x,text:e.target.value}:x)}:v)}:p)}))}/></Field>)}</details>)}</>}
      <details><summary>编辑完整页面结构 JSON</summary><Field label="网站结构 JSON"><textarea rows={14} value={raw} onChange={e=>setRaw(e.target.value)}/></Field><Button variant="secondary" onClick={()=>{try{const spec=JSON.parse(raw);validateSite(spec,new Set(project.assets.map(a=>a.id)));change(()=>spec);notice('结构已更新，请点击更新预览与源码。');}catch(e){notice(e instanceof Error?e.message:'结构无效。');}}}>应用结构编辑</Button></details>
      <div className="generation-row"><span className="muted">手动编辑后重新打包不调用 AI。</span><Button disabled={generation?.busy} onClick={()=>generation?.run('website-build')}>更新预览与源码</Button></div></section>
      <section className="surface"><h3>已采用的网站</h3>{dirty&&<p role="status">文案或结构已修改，下方仍为上次采用的版本；更新预览后采用新结果。</p>}{site.spec.limitations.length>0&&<p>尚未实现的要求：{site.spec.limitations.join('；')}</p>}{site.previewFileId&&<WebsitePreview fileId={site.previewFileId}/>}<div className="output-actions">{site.zipFileId&&<DownloadFile fileId={site.zipFileId} name="网站源码.zip">下载网站源码 ZIP</DownloadFile>}</div><p className="muted">解压后打开 index.html 即可离线运行。</p></section></>}
    </div>;
}
