'use client';
import {useState,useRef} from 'react';
import {Button,Field,AssetImage,Modal} from '@/components/workbench/ui';
import {TYPE_LABELS,CONTENT_SECTIONS,type Project,type ImageAsset,type WorkType,type WebsiteSource,type Concept} from '@/features/projects/model';
import {workflowInputs,flowWarnings,restoreRecord,sourceLabel,inheritWorkType,projectForType,selectedNovelConcepts,fingerprint} from '@/lib/workbench/workflow.mjs';
import {websiteRequestSource} from '@/lib/workbench/prompts.mjs';
import {outputUrl,uploadOutput} from '@/features/projects/server-store';
import type {EditProject,Notice} from './stages';
import type {GenerationControls} from './generation-api';

function readableValue(value:unknown):unknown {
  if(Array.isArray(value))return value.map(readableValue);
  if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>!/(Id|Ids)$/.test(key)&&!['id','source','basis','promptBasis','fingerprint','inheritedFrom'].includes(key)).map(([key,v])=>[key,readableValue(v)]));
  return value;
}
const sourceStage=(key:string)=>/^(idea|brief|culture|title)$/.test(key)?0:key.startsWith('content:')||key==='transfer'?1:/^(art|reference:)/.test(key)?2:/^(concept:|image:)/.test(key)?3:4;
export function InputSummary({project,kind,args={},edit}:{project:Project;kind:string;args?:Record<string,unknown>;edit?:EditProject}) {
  const inputs=workflowInputs(project,kind,args);
  const [preview,setPreview]=useState<ImageAsset|null>(null);
  const jump=(key:string)=>edit?.(p=>({...p,stage:sourceStage(key)}));
  return <details className="workflow-inputs"><summary>本次创作依据 · {inputs.length} 项</summary><p className="muted">沿用已保存的当前成果。任务提交后可在结果卡核对实际输入；未采用候选不会自动加入。</p><div className="workflow-source-list">{inputs.map(input=>input.role==='attached-image'?<div key={input.key}><button type="button" className="image-button" aria-label={'放大依据图片 '+input.label} onClick={()=>setPreview(project.assets.find(a=>a.id===input.key.split(':')[1])||null)}><AssetImage asset={project.assets.find(a=>a.id===input.key.split(':')[1])} alt={input.label}/></button><span>{input.label} · 实际图片附件</span>{edit&&sourceStage(input.key)!==project.stage&&<Button variant="ghost" onClick={()=>jump(input.key)}>查看来源阶段</Button>}</div>:<details key={input.key}><summary>{input.label}</summary><pre>{typeof input.value==='string'?input.value:JSON.stringify(readableValue(input.value),null,2)}</pre>{edit&&sourceStage(input.key)!==project.stage&&<Button variant="ghost" onClick={()=>jump(input.key)}>查看来源阶段</Button>}</details>)}</div>{kind==='novel'&&<p className="muted">正文使用已确认的对象文字设定；本次文字接口不附图片。</p>}{preview&&<Modal title={preview.name} onClose={()=>setPreview(null)}><AssetImage asset={preview} alt={preview.name} className="lightbox-image"/></Modal>}</details>;
}
export function ReferencePicker({project,selected,onSelect,multiple=false,label='上一阶段已保存概念图',includeExisting=true}:{project:Project;selected:string[];onSelect:(ids:string[])=>void;multiple?:boolean;label?:string;includeExisting?:boolean}) {
  const [preview,setPreview]=useState<ImageAsset|null>(null);
  const saved=new Set(project.concepts.map(c=>c.savedAssetId));
  const assets=project.assets.filter(a=>saved.has(a.id)||(includeExisting&&selected.includes(a.id)));
  return <div className="workflow-reference-picker"><p className="document-label">{label}</p>{assets.length?<div className="workflow-image-grid">{assets.map(a=>{const chosen=selected.includes(a.id);const objects=project.concepts.filter(c=>c.savedAssetId===a.id);return <article key={a.id} className={chosen?'is-selected':''}><button type="button" aria-pressed={chosen} aria-label={'选择参考 '+(objects.map(c=>c.name).join('、')||a.name)} onClick={()=>onSelect(multiple?(chosen?selected.filter(id=>id!==a.id):[...selected,a.id]):chosen?[]:[a.id])}><AssetImage asset={a} alt={a.name}/><strong>{objects.map(c=>c.name).join('、')||a.name}</strong><span>{chosen?'已选择':saved.has(a.id)?'已保存概念图':'已有选择 · 保留原图'}</span></button><Button variant="ghost" onClick={()=>setPreview(a)}>放大查看</Button></article>;})}</div>:<p className="muted">上一阶段还没有已保存概念图。可以先回到概念图阶段保存，也可以继续纯文字创作。</p>}{preview&&<Modal title={preview.name} onClose={()=>setPreview(null)}><AssetImage asset={preview} alt={preview.name} className="lightbox-image"/></Modal>}</div>;
}
export function ObjectBindings({project,concept,edit}:{project:Project;concept:Concept;edit:EditProject}) {
  const change=(patch:Partial<Concept>)=>edit(p=>({...p,concepts:p.concepts.map(c=>c.id===concept.id?{...c,...patch}:c)}));
  return <details className="workflow-object-bindings"><summary>对象来源、图片用途与继续参考</summary><p className="muted">默认从对应内容类别继承；可明确指定来源小节。参考图片将实际附带。</p><div className="inline-actions">{CONTENT_SECTIONS[project.type].filter(section=>project.content[project.type][section.key]).map(section=><label key={section.key}><input type="checkbox" checked={concept.sourceKeys?.includes(section.key)||false} onChange={e=>change({sourceKeys:e.target.checked?[...(concept.sourceKeys||[]),section.key]:(concept.sourceKeys||[]).filter(k=>k!==section.key)})}/>{section.label}</label>)}</div><Field label={'图片用途 · '+concept.name}><textarea rows={2} value={concept.usage||''} placeholder={project.type==='website'?'例如：作品详情页的物件照片，只作内容素材':'例如：保留主体形体，继续完善材质或准备另一视角'} onChange={e=>change({usage:e.target.value})}/></Field><ReferencePicker project={project} selected={concept.referenceAssetIds||[]} multiple onSelect={ids=>change({referenceAssetIds:ids})} label="本轮继续使用的已保存形象"/><InputSummary project={project} edit={edit} kind="image" args={{objectId:concept.id,action:'generate'}}/></details>;
}
export function NovelReferences({project,edit}:{project:Project;edit:EditProject}) {
  const selected=selectedNovelConcepts(project).map(c=>c.id);
  return <details><summary>沿用人物、场景与物件设定</summary><p className="muted">默认沿用已保存概念图对应的文字设定；可选择其他已确认对象。未记录的图片细节不会自动写进正文。</p>{project.concepts.map(c=><label className="workflow-check" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>edit(p=>({...p,novelReferenceIds:e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id)}))}/><span>{c.name}<small>{c.description}</small></span></label>)}</details>;
}
export function WorkflowPanel({project,edit,notice}:{project:Project;edit:EditProject;notice:Notice}) {
  const [from,setFrom]=useState<WorkType>('undecided');const [inheritArt,setInheritArt]=useState(false);const [inheritBrief,setInheritBrief]=useState(true);const [inheritContent,setInheritContent]=useState(true);const [ids,setIds]=useState<string[]>([]);
  const choices=Object.keys(project.variants||{}).filter(t=>t!==project.type) as WorkType[];
  const sourceType=choices.includes(from)?from:choices[0];const source=sourceType?projectForType(project,sourceType):null;
  const kind=['creative','content','art','objects',project.type==='novel'?'novel':project.type==='website'?'website':project.type==='video'?'video-shot':'design-package'][project.stage];
  const warnings=flowWarnings(project);const records=(project.flow?.records||[]).filter(r=>r.type===project.type).toReversed();
  const targetNames=(target:string)=>sourceLabel(project,target);
  const showInputs=project.stage<4||project.type==='website';
  if(!showInputs&&!warnings.length&&!choices.length&&!records.length&&!project.transfer)return null;
  return <section className="surface workflow-panel">{showInputs&&<InputSummary project={project} edit={edit} kind={kind}/>}{warnings.length>0&&<details><summary>相关依据已有更新 · {warnings.length} 项</summary>{warnings.map(w=><p key={w.target}>{targetNames(w.target)}：{w.changes.map(c=>c.label).join('、')}已变化。当前成果和文件保留，请核对需要完善的部分。</p>)}</details>}
    {choices.length>0&&<details><summary>从其他作品类型沿用资料</summary><Field label="资料来源类型"><select value={sourceType} onChange={e=>{setFrom(e.target.value as WorkType);setIds([]);}}>{choices.map(type=><option key={type} value={type}>{TYPE_LABELS[type]}</option>)}</select></Field><div className="inline-actions"><label><input type="checkbox" checked={inheritBrief} onChange={e=>setInheritBrief(e.target.checked)}/>沿用创意方案</label><label><input type="checkbox" checked={inheritContent} onChange={e=>setInheritContent(e.target.checked)}/>将原内容作为适配资料</label><label><input type="checkbox" checked={inheritArt} onChange={e=>setInheritArt(e.target.checked)}/>沿用美术与风格参考</label></div>{source&&<><details><summary>查看将沿用的原文</summary><pre className="workflow-text">{JSON.stringify({brief:source.brief,content:project.content[sourceType]},null,2)}</pre></details><ReferencePicker project={source} selected={source.concepts.filter(c=>ids.includes(c.id)).map(c=>c.savedAssetId).filter((id):id is string=>Boolean(id))} multiple label="明确继续使用的概念对象" onSelect={assets=>setIds(source.concepts.filter(c=>assets.includes(c.savedAssetId||'')).map(c=>c.id))}/></>}<Button variant="secondary" onClick={()=>{edit(p=>inheritWorkType(p,sourceType,{brief:inheritBrief,content:inheritContent,art:inheritArt,conceptIds:ids}));notice('已沿用选定资料；内容会在下一次生成时适配当前类型，原类型草稿保留。');}}>沿用选定资料</Button></details>}
    {project.transfer&&<p className="muted">本类型内容生成将参考 {TYPE_LABELS[project.transfer.from]} 的转入资料。<Button variant="ghost" onClick={()=>edit(p=>({...p,transfer:undefined}))}>停止引用转入资料</Button></p>}
    {records.length>0&&<details><summary>已保存成果版本 · {records.length}</summary><p className="muted">恢复会形成当前草稿的新版本；已生成文件继续保留。旧记录未标明来源时，不推断其生成依据。</p><div className="workflow-history">{records.map(r=><details key={r.id}><summary>{targetNames(r.target)} · {new Date(r.createdAt).toLocaleString('zh-CN')} · {{generated:'已采用生成成果',manual:'手工保存',legacy:'旧记录，来源未知',restore:'恢复版本'}[r.origin]||r.origin}</summary><pre>{typeof r.value==='string'?r.value:JSON.stringify(readableValue(r.value),null,2)}</pre><Button variant="secondary" onClick={()=>{try{edit(p=>restoreRecord(p,r.id));notice('已恢复为当前草稿，后续成果仍保留。');}catch(e){notice(e instanceof Error?e.message:'恢复失败');}}}>恢复此版本</Button></details>)}</div></details>}
  </section>;
}
export function WebsiteSourcePanel({project,edit,notice}:{project:Project;edit:EditProject;notice:Notice}) {
  const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [showPreview,setShowPreview]=useState(false);const source=project.websiteSource,candidate=project.websiteSourceCandidate;
  return <section className="surface" id="website-step-3"><h3>3. 导入并检查网站</h3><p>把 WorkBuddy 交付的网站源码 ZIP 导入这里。确认后采用，可预览静态页面、下载源码，并继续提出修改。</p><Button variant="secondary" disabled={busy} onClick={()=>input.current?.click()}>{busy?'正在检查源码包…':'导入网站源码 ZIP 为候选'}</Button><input hidden type="file" accept=".zip,application/zip" ref={input} aria-label="导入网站源码 ZIP" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setBusy(true);try{const result=await uploadOutput(file,'website-source') as unknown as WebsiteSource;edit(p=>({...p,websiteSourceCandidate:result}));notice('源码候选已保存；ZIP 结构检查不代表网站功能已通过。');}catch(error){notice(error instanceof Error?error.message:'源码导入失败');}finally{setBusy(false);}}}/>
    {!source&&!candidate&&<div className="website-source-empty">还没有收到网站源码。先完成上一步的网站制作，再导入结果；生成任务包后不会自动出现网站。</div>}
    {candidate&&<div><p>待采用源码 · {candidate.entryCount} 个文件</p>{(['description','instructions','verification'] as const).map((key,i)=><Field key={key} label={['交付说明','运行说明','执行端实际检查记录'][i]}><textarea rows={2} value={candidate[key]} onChange={e=>edit(p=>({...p,websiteSourceCandidate:{...p.websiteSourceCandidate!,[key]:e.target.value}}))}/></Field>)}<p className="muted">未关联生成任务的导入文件，来源标为用户提供；不会虚构任务依据。</p><a href={outputUrl(candidate.fileId)} download>下载候选源码核对</a><Button onClick={()=>{if(candidate.requestSource&&candidate.requestSource!==websiteRequestSource(project)){notice('相关网站依据已变化，候选保留，请核对后重新交接。');return;}edit(p=>({...p,websiteSource:p.websiteSourceCandidate,websiteSourceCandidate:undefined}));notice('已采用源码；后续网站任务会携带这一版文件。');}}>采用为下一轮源码</Button></div>}
    {source&&<div><p>已采用：{source.description} · {source.entryCount} 个文件</p><a href={outputUrl(source.fileId)} download>下载当前源码 ZIP</a><details><summary>运行与验证记录</summary><p className="creative-text">{source.instructions||'尚未提供运行说明'}</p><p className="creative-text">{source.verification}</p></details>{source.previewPath&&<><Button variant="ghost" onClick={()=>setShowPreview(!showPreview)}>{showPreview?'收起静态预览':'打开静态 HTML 预览'}</Button><p className="muted">预览仅运行包内静态页面；网络接口、服务端与构建步骤须在执行端验证。</p>{showPreview&&<div className="site-frame"><iframe title="已采用源码的静态预览" sandbox="allow-scripts" referrerPolicy="no-referrer" src={'/api/workbench/data/source-preview/'+source.fileId+'/'+source.previewPath.split('/').map(encodeURIComponent).join('/')}/></div>}</>}</div>}
  </section>;
}
export function DesignDelivery({project,edit,generation}:{project:Project;edit:EditProject;generation?:GenerationControls}) {
  const current=project.designPackage?.source===fingerprint(workflowInputs(project,'design-package'));
  return <section className="surface"><h3>{project.type==='craft'?'3D 前期设计资料交付':'跨媒介创作资料'}</h3><p>{project.type==='craft'?'汇集当前形体、文化依据、美术与实际概念图，供后续 3D 制作继续完善。当前没有生成模型文件。':'保存当前创意、内容与已采用视觉成果；确定作品类型后可选择沿用并适配。'}</p><InputSummary project={project} edit={edit} kind="design-package"/><Field label="下一步完善与交付要求"><textarea rows={3} value={project.delivery.notes} onChange={e=>edit(p=>({...p,delivery:{...p.delivery,notes:e.target.value}}))}/></Field><Button disabled={generation?.busy} onClick={()=>generation?.run('design-package')}>保存设计资料包</Button>{project.designPackage&&<p>{current?'已采用资料包':'已保留旧资料包，依据已有更新'} · <a href={outputUrl(project.designPackage.fileId)} download>下载资料与实际图片 ZIP</a></p>}</section>;
}
