import { zipSync, strToU8 } from 'fflate';
import { validateSite } from './output-contract.mjs';

export const SITE_CSP = "sandbox allow-scripts; default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; font-src 'none'; connect-src 'none'; form-action 'none'; base-uri 'none'";
const escape = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css = `*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:17px/1.8 system-ui,sans-serif}a{color:inherit}button,input{font:inherit}button,a,input,summary{outline-offset:5px}header,main,footer{max-width:1180px;margin:auto;padding:30px 6vw}header{display:flex;align-items:center;justify-content:space-between;gap:24px;flex-wrap:wrap;border-bottom:1px solid var(--line)}.brand{font-weight:700;text-decoration:none}nav{display:flex;gap:22px;flex-wrap:wrap}nav a{text-decoration:none;border-bottom:2px solid transparent}nav a[aria-current=page]{border-color:var(--accent)}.eyebrow{color:var(--accent);font-size:13px;letter-spacing:.2em}h1{font:clamp(40px,7vw,86px)/1.15 Georgia,'Microsoft YaHei',serif;margin:25px 0;max-width:950px}h2{font-size:30px;margin:0 0 16px}h3{font-size:20px}.intro{font-size:21px;max-width:750px}.body{white-space:pre-wrap}.hero{padding:54px 0 60px}section{padding:32px 0;border-top:1px solid var(--line)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:24px}.card{border:1px solid var(--line);border-radius:12px;padding:22px;background:var(--card)}.card img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:8px}.tag{font-size:13px;color:var(--accent)}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}.filters button{padding:5px 15px;border:1px solid var(--line);border-radius:100px;background:var(--bg);color:var(--ink);cursor:pointer}.filters button[aria-pressed=true]{background:var(--ink);color:var(--bg)}input{width:100%;padding:12px;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:6px}details{border-bottom:1px solid var(--line);padding:16px 0}summary{cursor:pointer;font-weight:600}footer{border-top:1px solid var(--line);font-size:14px}.empty{padding:24px;color:var(--accent)}[hidden]{display:none!important}@media(max-width:600px){header,main,footer{padding:22px}.hero{padding:30px 0}nav{gap:14px}h2{font-size:25px}}`;
const js = `(()=>{'use strict';const pages=[...document.querySelectorAll('[data-page]')];const links=[...document.querySelectorAll('nav a')];function route(){const key=location.hash.slice(1);const page=pages.find(p=>p.id===key)||pages[0];pages.forEach(p=>p.hidden=p!==page);links.forEach(a=>{if(a.hash==='#'+page.id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});document.title=page.dataset.title+' · '+document.body.dataset.title;}window.addEventListener('hashchange',route);route();document.querySelectorAll('[data-gallery]').forEach(g=>{const input=g.querySelector('input');const cards=[...g.querySelectorAll('[data-card]')];const buttons=[...g.querySelectorAll('button[data-tag]')];let tag='';function filter(){let count=0;cards.forEach(c=>{c.hidden=!!((tag&&c.dataset.tag!==tag)||!c.textContent.toLocaleLowerCase().includes(input.value.trim().toLocaleLowerCase()));if(!c.hidden)count++;});g.querySelector('[data-empty]').hidden=count>0;g.querySelector('[data-count]').textContent='显示 '+count+' 项';}input.addEventListener('input',filter);buttons.forEach(b=>b.addEventListener('click',()=>{tag=b.dataset.tag;buttons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter()}));filter();});})();`;
export async function buildWebsite(spec, project, repository) {
  validateSite(spec,new Set(project.assets.map(a=>a.id)));
  const files={}; const pictures=new Map();
  for(const page of spec.pages) for(const section of page.sections) for(const item of section.items) if(item.assetId&&!pictures.has(item.assetId)) {
    const a=project.assets.find(a=>a.id===item.assetId);const bytes=await repository.media(a.fileId);
    pictures.set(item.assetId,'data:image/png;base64,'+bytes.toString('base64'));files['assets/'+a.fileId+'.png']=bytes;
  }
  let sequence=0;
  const pages=spec.pages.map(page=>`<article data-page id="${escape(page.id)}" data-title="${escape(page.title)}"><div class="hero"><div class="eyebrow">${escape(spec.title)}</div><h1>${escape(page.title)}</h1><p class="intro body">${escape(page.intro)}</p></div>${page.sections.map(s=>{
    const key='gallery-'+sequence++;
    const items=s.items.map(item=>s.kind==='faq'?`<details><summary>${escape(item.title)}</summary><p class="body">${escape(item.text)}</p></details>`:`<div class="card" data-card data-tag="${escape(item.tag)}">${item.assetId?`<img src="${pictures.get(item.assetId)}" alt="${escape(item.title)}" loading="lazy">`:''}<span class="tag">${escape(item.tag)}</span><h3>${escape(item.title)}</h3><p class="body">${escape(item.text)}</p></div>`).join('');
    const tags=[...new Set(s.items.map(i=>i.tag).filter(Boolean))];
    return `<section ${s.kind==='gallery'?'data-gallery':''}><h2>${escape(s.title)}</h2><p class="body">${escape(s.body)}</p>${s.kind==='gallery'?`<label for="${key}">搜索${escape(s.title)}</label><input id="${key}" type="search" placeholder="输入关键词"><div class="filters"><button type="button" data-tag="" aria-pressed="true">全部</button>${tags.map(t=>`<button type="button" data-tag="${escape(t)}" aria-pressed="false">${escape(t)}</button>`).join('')}</div><p data-count role="status"></p>`:''}<div class="${s.kind==='faq'?'faq':'grid'}">${items}</div>${s.kind==='gallery'?'<p data-empty class="empty" hidden>没有符合条件的内容，请换一个关键词或分类。</p>':''}</section>`;
  }).join('')}</article>`).join('');
  const night=spec.theme==='night';
  const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escape(spec.description)}"><meta http-equiv="Content-Security-Policy" content="${SITE_CSP.replace('sandbox allow-scripts; ','')}"><title>${escape(spec.title)}</title><style>:root{--accent:${spec.accent};--bg:${night?'#172d29':'#f7f3ea'};--ink:${night?'#f7f3ea':'#253f36'};--card:${night?'#203a34':'#fffcf6'};--line:${night?'#496059':'#d8ddcf'}}${css}</style></head><body data-title="${escape(spec.title)}"><header><a class="brand" href="#${escape(spec.pages[0].id)}">${escape(spec.title)}</a><nav aria-label="主导航">${spec.pages.map(p=>`<a href="#${escape(p.id)}">${escape(p.title)}</a>`).join('')}</nav></header><main>${pages}</main><footer>${escape(spec.description)}</footer><script>${js}</script></body></html>`;
  files['index.html']=strToU8(html);files['styles.css']=strToU8(css);files['app.js']=strToU8(js);files['site.json']=strToU8(JSON.stringify(spec,null,2));
  files['README.md']=strToU8(`# ${spec.title}\n\n解压后双击 index.html 即可离线运行，无需安装依赖。导航、搜索与分类筛选在本机浏览器运行，FAQ 可展开。页面与图片已内嵌到 HTML，同时附带独立素材、样式和脚本供编辑参考。修改独立 CSS / JS 后，需同步替换 index.html 中对应 style / script 内容。\n\n## 页面\n${spec.pages.map(p=>'- '+p.title).join('\n')}\n\n## 交付边界\n纯静态网站，无登录、支付、后台、表单提交、数据库。\n${spec.limitations.map(s=>'- '+s).join('\n')}\n\n## 素材来源\n${project.assets.filter(a=>pictures.has(a.id)).map(a=>'- '+a.name+'：'+(a.source?.provider||'用户提供')+'；'+(a.source?.model||'来源待用户核实')).join('\n')}\n\n文化事实与素材使用范围请按项目已确认资料核实。\n`);
  const preview=await repository.putOutput(Buffer.from(html),'html'); const zip=await repository.putOutput(Buffer.from(zipSync(files,{level:6})),'zip');
  return {spec,builtSpec:spec,previewFileId:preview.fileId,zipFileId:zip.fileId};
}
